#!/usr/bin/env node
/**
 * build.js — Read products/*.md → generate products-data.js
 * Run: node build.js
 * Cloudflare Pages build command: node build.js
 */
const fs = require('fs');
const path = require('path');

const productsDir = path.join(__dirname, 'products');
const outFile = path.join(__dirname, 'products-data.js');

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const fm = {};
  match[1].split('\n').forEach(line => {
    const idx = line.indexOf(':');
    if (idx > 0) {
      const key = line.slice(0, idx).trim();
      let val = line.slice(idx + 1).trim();
      // Remove surrounding quotes
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      if (val === 'true') val = true;
      else if (val === 'false') val = false;
      else if (/^\d+$/.test(val)) val = parseInt(val);
      fm[key] = val;
    }
  });
  return fm;
}

// Read all .md files from products/
const products = [];
if (fs.existsSync(productsDir)) {
  const files = fs.readdirSync(productsDir).filter(f => f.endsWith('.md')).sort();
  for (const file of files) {
    const content = fs.readFileSync(path.join(productsDir, file), 'utf8');
    const data = parseFrontmatter(content);
    data.slug = file.replace(/\.md$/, '');
    if (!data.order) data.order = 999;
    products.push(data);
  }
}

// Sort by order
products.sort((a, b) => (a.order || 0) - (b.order || 0));

// Generate JS file
const js = `// Auto-generated by build.js — DO NOT EDIT
const PRODUCTS_DATA = ${JSON.stringify(products, null, 2)};
`;

fs.writeFileSync(outFile, js, 'utf8');
console.log(`Generated products-data.js with ${products.length} products`);
