#!/usr/bin/env node
/**
 * build.js — Read products/*.md → generate products-data.js + product detail pages
 */
const fs = require('fs');
const path = require('path');

const productsDir = path.join(__dirname, 'products');
const dataFile = path.join(__dirname, 'products-data.js');
const productsPageDir = path.join(__dirname, 'products-pages');

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return { _body: content };
  const fm = {};
  match[1].split('\n').forEach(line => {
    const idx = line.indexOf(':');
    if (idx > 0) {
      const key = line.slice(0, idx).trim();
      let val = line.slice(idx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      if (val === 'true') val = true;
      else if (val === 'false') val = false;
      else if (/^\d+$/.test(val)) val = parseInt(val);
      fm[key] = val;
    }
  });
  const bodyStart = match[0].length;
  fm._body = content.slice(bodyStart).trim();
  return fm;
}

function parseYamlList(val) {
  if (Array.isArray(val)) return val;
  if (typeof val === 'string') {
    try {
      return JSON.parse(val);
    } catch { return [val]; }
  }
  return [];
}

// Read all products
const products = [];
if (fs.existsSync(productsDir)) {
  const files = fs.readdirSync(productsDir).filter(f => f.endsWith('.md')).sort();
  for (const file of files) {
    const content = fs.readFileSync(path.join(productsDir, file), 'utf8');
    const data = parseFrontmatter(content);
    data.slug = file.replace(/\.md$/, '');
    if (!data.order) data.order = 999;
    products.push(data);
  }
}
products.sort((a, b) => (a.order || 0) - (b.order || 0));

// 1. Generate products-data.js
const js = `// Auto-generated by build.js — DO NOT EDIT
const PRODUCTS_DATA = ${JSON.stringify(products.map(p => ({
  title: p.title,
  category: p.category,
  description: p.description,
  image: p.image,
  badge: p.badge,
  order: p.order,
  slug: p.slug,
  anchor: p.anchor
})), null, 2)};
`;
fs.writeFileSync(dataFile, js, 'utf8');
console.log(`Generated products-data.js with ${products.length} products`);

// 2. Generate product detail pages
if (!fs.existsSync(productsPageDir)) fs.mkdirSync(productsPageDir, { recursive: true });

const categorySectionMap = {
  'Temperature & Humidity': '1',
  'RS485 Industrial': '2',
  'Analog (4~20mA)': '3',
  'Agriculture': '4',
  'Accessories': 'A'
};

for (const p of products) {
  const sectionNum = categorySectionMap[p.category] || '?';
  const features = parseYamlList(p.features);
  const specs = parseYamlList(p.specs);
  const applications = parseYamlList(p.applications);
  const bodyHtml = p._body ? p._body : '';

  let featuresHtml = '';
  if (features.length) {
    featuresHtml = `<div class="detail-section"><h3>✨ Key Features</h3><ul>${features.map(f => `<li>${f}</li>`).join('')}</ul></div>`;
  }

  let specsHtml = '';
  if (specs.length) {
    specsHtml = `<div class="detail-section"><h3>📋 Technical Specifications</h3><table class="spec-table"><tbody>${specs.map(s => {
      const parts = s.split(':');
      if (parts.length >= 2) return `<tr><th>${parts[0].trim()}</th><td>${parts.slice(1).join(':').trim()}</td></tr>`;
      return `<tr><td colspan="2">${s}</td></tr>`;
    }).join('')}</tbody></table></div>`;
  }

  let appsHtml = '';
  if (applications.length) {
    appsHtml = `<div class="detail-section"><h3>🎯 Typical Applications</h3><ul>${applications.map(a => `<li>${a}</li>`).join('')}</ul></div>`;
  }

  let bodySectionHtml = '';
  if (bodyHtml) {
    bodySectionHtml = `<div class="detail-section"><h3>📖 Detailed Description</h3><div class="detail-body">${bodyHtml}</div></div>`;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${p.title} — SpringBees Hub</title>
    <link rel="stylesheet" href="/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="icon" href="/assets/springbee-icon.png" type="image/png">
    <style>
      .detail-page { max-width: 800px; margin: 0 auto; padding: 40px 24px; }
      .detail-breadcrumb { font-size: 13px; color: var(--text-muted); margin-bottom: 20px; }
      .detail-breadcrumb a { color: var(--gold); text-decoration: none; }
      .detail-breadcrumb a:hover { text-decoration: underline; }
      .detail-title { font-size: 2rem; font-weight: 700; margin-bottom: 8px; color: var(--navy); }
      .detail-category { display: inline-block; background: var(--gold); color: #fff; padding: 2px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; margin-bottom: 16px; }
      .detail-badge { display: inline-block; background: #e74c3c; color: #fff; padding: 2px 10px; border-radius: 10px; font-size: 11px; font-weight: 600; margin-left: 8px; }
      .detail-desc { font-size: 15px; color: var(--text-light); line-height: 1.7; margin-bottom: 24px; }
      .detail-image { max-width: 100%; border-radius: 12px; margin-bottom: 24px; }
      .detail-section { margin-bottom: 28px; }
      .detail-section h3 { font-size: 1.1rem; font-weight: 600; color: var(--navy); margin-bottom: 12px; border-bottom: 2px solid var(--gold); padding-bottom: 6px; display: inline-block; }
      .detail-section ul { padding-left: 20px; line-height: 1.8; }
      .detail-section li { margin-bottom: 4px; }
      .spec-table { width: 100%; border-collapse: collapse; }
      .spec-table th, .spec-table td { text-align: left; padding: 10px 14px; border-bottom: 1px solid var(--border); font-size: 14px; }
      .spec-table th { width: 40%; color: var(--navy); font-weight: 600; background: #f8f9fa; }
      .detail-body { line-height: 1.8; font-size: 14px; }
      .detail-body p { margin-bottom: 12px; }
      .detail-back { display: inline-block; margin-top: 32px; padding: 10px 24px; background: var(--navy); color: #fff; border-radius: 8px; text-decoration: none; font-weight: 600; transition: background 0.2s; }
      .detail-back:hover { background: var(--gold); }
    </style>
</head>
<body>
    <nav class="top-nav">
        <a href="/" class="nav-brand">
            <img src="/assets/springbee-icon.png" alt="SpringBees" class="nav-logo">
            <span class="brand-name">Spring<span class="gold">Bee</span> Hub</span>
        </a>
        <div class="nav-links">
            <a href="/">Home</a>
            <a href="/#sensors">Products</a>
            <a href="/#network">Network</a>
            <a href="/#downloads">Downloads</a>
            <a href="/faq">FAQ</a>
        </div>
        <div class="nav-right-group">
            <a href="https://www.iot-bees.com" class="nav-badge" target="_blank" rel="noopener">🛒 Sensor Selection Store</a>
        </div>
    </nav>

    <div class="detail-page">
        <div class="detail-breadcrumb">
            <a href="/">Home</a> / <a href="/#sensors">Products</a> / ${p.title}
        </div>
        ${p.image ? `<img src="${p.image}" alt="${p.title}" class="detail-image">` : ''}
        <h1 class="detail-title">${p.title}${p.badge ? `<span class="detail-badge">${p.badge}</span>` : ''}</h1>
        <span class="detail-category">Section ${sectionNum} · ${p.category}</span>
        ${p.description ? `<p class="detail-desc">${p.description}</p>` : ''}
        ${featuresHtml}
        ${specsHtml}
        ${appsHtml}
        ${bodySectionHtml}
        <a href="/#sensors" class="detail-back">← Back to Product Hive</a>
    </div>
</body>
</html>`;

  fs.writeFileSync(path.join(productsPageDir, `${p.slug}.html`), html, 'utf8');
}

console.log(`Generated ${products.length} product detail pages in products-pages/`);

// 3. Copy product pages to site root for Cloudflare Pages serving
const siteRoot = __dirname;
for (const p of products) {
  const src = path.join(productsPageDir, `${p.slug}.html`);
  const dst = path.join(siteRoot, `${p.slug}.html`);
  if (fs.existsSync(src)) fs.copyFileSync(src, dst);
}
console.log(`Copied ${products.length} product pages to site root`);
