// Auto-generated by build.js — DO NOT EDIT
const PRODUCTS_DATA = [
  {
    "title": "T68DL",
    "category": "Temperature & Humidity",
    "order": 1,
    "slug": "t68dl"
  },
  {
    "title": "Indoor TH Sensor",
    "category": "Temperature & Humidity",
    "order": 2,
    "slug": "indoor-th-sensor"
  },
  {
    "title": "Liquid Level",
    "category": "RS485 Industrial",
    "order": 3,
    "slug": "liquid-level"
  },
  {
    "title": "Pressure",
    "category": "RS485 Industrial",
    "order": 4,
    "slug": "pressure"
  },
  {
    "title": "Flow Meter",
    "category": "RS485 Industrial",
    "order": 5,
    "slug": "flow-meter"
  },
  {
    "title": "4~20mA Sensor Adapter",
    "category": "Analog (4~20mA)",
    "order": 6,
    "slug": "4-20ma-sensor-adapter"
  },
  {
    "title": "Pressure Transmitter",
    "category": "Analog (4~20mA)",
    "order": 7,
    "slug": "pressure-transmitter"
  },
  {
    "title": "Soil Moisture & Temp",
    "category": "Agriculture",
    "order": 8,
    "slug": "soil-moisture-temp"
  },
  {
    "title": "Weather Station",
    "category": "Agriculture",
    "order": 9,
    "slug": "weather-station"
  },
  {
    "title": "Soil NPK",
    "category": "Agriculture",
    "order": 10,
    "slug": "soil-npk"
  },
  {
    "title": "LoRa Antenna",
    "category": "Accessories",
    "order": 11,
    "slug": "lora-antenna",
    "anchor": "accessories-antenna"
  },
  {
    "title": "UPS Power",
    "category": "Accessories",
    "order": 12,
    "slug": "ups-power",
    "anchor": "accessories-ups"
  },
  {
    "title": "Lightning Prot.",
    "category": "Accessories",
    "order": 13,
    "slug": "lightning-protection",
    "anchor": "accessories-lightning"
  }
];
